# Site settings
title: Cheatsheets
description: Concise, easy-to-reference cheatsheets for various programming languages and technologies
# baseurl: "" # The subpath of your site, e.g. /blog
# url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: jekyll-theme-minimal
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# GitHub Pages settings
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/architect@v0.2.0

minima:
  social_links:
    - platform: twitter
      user_url: "https://www.twitter.com/ashababnoor"
      title:  My profile at X (formerly Twitter)