# Site settings
title: Cheatsheets
description: Concise, easy-to-reference cheatsheets for various programming languages and technologies
# baseurl: "" # The subpath of your site, e.g. /blog
# url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: jekyll-theme-minimal
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# GitHub Pages settings
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/architect@v0.2.0

header_pages:
  - README.md

minima:
  # Generate social links in footer.
  social_links:
   - { platform: github,         user_url: "https://github.com/ashababnoor/cheatsheet" }
   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=b6chKnEAAAAJ" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ashababnoor" }
   - { platform: twitter,        user_url: "https://twitter.com/ashababnoor" }
   - { platform: x,              user_url: "https://x.com/ashababnoor" }
