# Site settings
title: Cheatsheets
description: Concise, easy-to-reference cheatsheets for various programming languages and technologies
author:
  name: Shabab Noor
  email: ashababnoor@gmail.com

permalink: /404.md

# Build settings
# theme: jekyll-theme-minimal
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# GitHub Pages settings
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/architect@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0

header_pages:
  - README.md

minima:
  # Generate social links in footer.
  social_links:
   - { platform: github,         user_url: "https://github.com/ashababnoor/cheatsheet" }
   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=b6chKnEAAAAJ" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ashababnoor" }
   - { platform: twitter,        user_url: "https://twitter.com/ashababnoor" }
   - { platform: x,              user_url: "https://x.com/ashababnoor" }


markdown: kramdown
kramdown:
  math_engine: mathjax
